### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by devmor-j** [Rejdesu/purpleVoid#1]
Hey I just found your theme and starred it quickly :) it's a great work, Thanks for creating it.

Though there are some minor issues that I would like to mention, hope it's helpful:

- The caret color is very white I mean it's pure white and since it's a *void style* theme it's kinda out of harmony, maybe a grayish color can look better
- The auto-complete background color has very low contrast, making it hard to read what's been typed
- The primary and secondary blue colors are hard to distinguish and maybe a higher hue tone could reveal them better (look at Tmp and Println functions)
- Scrollbar seems to be almost invisible
- Some themes have a rainbow style for JSON files and it would feel more professional if purple void had the same feature

here are 2 pictures for notes above:

**White caret and low contrast intellisense**
![Screenshot_2023-08-24-19-50-53_1920x1080](https://github.com/Rejdesu/purpleVoid/assets/88786674/13dceb36-87d4-40e8-948f-05506cb21307)

**Rainbow JSON (taken from Dark Lavender theme)**
![Screenshot_2023-08-24-20-00-08_1920x1080](https://github.com/Rejdesu/purpleVoid/assets/88786674/7445ebce-d46a-4cb6-8250-d9eaddca3812)

These are just my takes, completely optional.

Overall I really like Purple Void and hope it grow. It has a nice palette and a lot of potential. Cheers :)

**Comment by Rejdesu** [comment]
I have implemented these changes. Thank you for using my theme. I appreciate your thoughts and input. I hope the changes are good enough.
